/**
 * Prune Palettes — remove unselected palette CSS files and rebuild _themes.css
 */
import { join } from 'node:path';
import { rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const ALL_PALETTES = [
  'azure', 'solaris', 'evergreen', 'rose', 'monochrome',
  'nordic', 'aquatica', 'abyss', 'neonoir', 'synthwave',
];

export async function prunePalettes(
  projectPath: string,
  selectedPalettes: string[],
  dryRun: boolean
): Promise<{ removed: number }> {
  const unselected = ALL_PALETTES.filter(p => !selectedPalettes.includes(p));
  let removed = 0;

  // Remove unselected palette CSS files
  for (const palette of unselected) {
    const cssFile = join(projectPath, `src/styles/palettes/${palette}.css`);

    if (dryRun) {
      console.log(`  [dry-run] Would remove: src/styles/palettes/${palette}.css`);
      removed++;
      continue;
    }

    try {
      if (existsSync(cssFile)) {
        await rm(cssFile);
        removed++;
      }
    } catch {
      // File doesn't exist
    }
  }

  // Rebuild _themes.css with only selected palette imports
  const themesContent = [
    '/* Theme Definitions — auto-generated by create-astroglass */',
    '',
    '@import "./palettes/_root.css";',
    ...selectedPalettes.map(p => `@import "./palettes/${p}.css";`),
    '',
  ].join('\n');

  if (dryRun) {
    console.log('  [dry-run] Would regenerate _themes.css');
  } else {
    await writeFile(join(projectPath, 'src/styles/_themes.css'), themesContent, 'utf-8');
  }

  return { removed };
}
